language: php
sudo: false

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3

cache:
  directories:
    - $HOME/.composer/cache/files

install: composer install

script: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
